### PR TITLE
#73 - Deleting unused files

### PR DESCRIPTION
**Pull request by ImmortalIdiot**
Deleted unused files: login and registration activities, journal, profile and settings view models.

### CODE REVIEW

**Comment by ImmortalIdiot** [comment]
Xandr070, help me delete unused xml files. I have already deleted activity_login.xml and activity_registration.xml

**Comment by Xandr070** [comment]
> Xandr070, help me delete unused xml files. I have already deleted activity_login.xml and activity_registration.xml

I will delete unnecessary drawable files

**Comment by ImmortalIdiot** [comment]
@Xandr070, can I merge this pr?

**Comment by Xandr070** [comment]
> @Xandr070, can I merge this pr?

fragment_registration.xml
@+id/scroll_container - @+id/registration_scroll_container
@+id/registration_container - @+id/registration_content_container
@+id/login_textview - @+id/registration_title_textview
@+id/reg_email_field - @+id/registration_email_field
@+id/reg_email - @+id/registration_email
@+id/reg_password_field - @+id/registration_password_field
@+id/reg_password - @+id/registration_password
@+id/password_confirmation_field - @+id/registration_password_confirmation_field
@+id/password_confirmation - @+id/registration_password_confirmation
@+id/progress_bar - @+id/registration_progress_bar
@+id/reg_button - @+id/registration_button
@+id/to_login - @+id/registration_to_login_textview
@+id/reg_student_id - @+id/registration_student_id_field
@+id/reg_student_id_field - @+id/registration_student_id

I will do the same for each xml file. Give me some time.

**Comment by Xandr070** [comment]
> > @Xandr070, can I merge this pr?
> 
> fragment_registration.xml @+id/scroll_container - @+id/registration_scroll_container @+id/registration_container - @+id/registration_content_container @+id/login_textview - @+id/registration_title_textview @+id/reg_email_field - @+id/registration_email_field @+id/reg_email - @+id/registration_email @+id/reg_password_field - @+id/registration_password_field @+id/reg_password - @+id/registration_password @+id/password_confirmation_field - @+id/registration_password_confirmation_field @+id/password_confirmation - @+id/registration_password_confirmation @+id/progress_bar - @+id/registration_progress_bar @+id/reg_button - @+id/registration_button @+id/to_login - @+id/registration_to_login_textview @+id/reg_student_id - @+id/registration_student_id_field @+id/reg_student_id_field - @+id/registration_student_id
> 
> I will do the same for each xml file. Give me some time.

@+id/parent_registration - @+id/login_Container
@+id/flow - @+id/login_flow
@+id/login_textview - @+id/login_title_textview
@+id/login_email_field - @+id/login_email_field
@+id/login_email - @+id/login_email
@+id/reg_student_id - @+id/login_student_id_field
@+id/reg_student_id_field - @+id/login_student_id
@+id/textInputLayout2 - @+id/login_password_field
@+id/login_password - @+id/login_password
@+id/login_Container - @+id/entrance_container
@+id/rememberMeCheckBox - @+id/login_remember_me_checkbox
@+id/login_button - @+id/login_button
@+id/to_registration - @+id/login_to_registration_textview
@+id/password_reset - @+id/login_password_reset_textview
@+id/progress_bar - @+id/login_progress_bar

fragment-login.xml

**Comment by Xandr070** [comment]
> @Xandr070, can I merge this pr?

@+id/dialog_forgot -> @+id/forgot_password_dialog
@+id/dialog_box -> @+id/forgot_password_dialog_box
@+id/forgotTitle -> @+id/forgot_password_title_textview
@+id/textInputLayout -> @+id/forgot_password_email_field
@+id/email_text_field -> @+id/forgot_password_email
@+id/reset_button -> @+id/forgot_password_reset_button
@+id/cancel_button -> @+id/forgot_password_cancel_button

forgot_dialog.xml     I won't change the fragment_settings, because everything is fine there

**Review by Xandr070 — DISMISSED** [review]

**Comment by ImmortalIdiot** [comment]
@Xandr070, I will change id names in the next pr. In this pr I delete unnecessary files

**Review by NN171 — APPROVED** [review]

**Pull request merged**
