### PR TITLE
#54 - Sync app with local server

### LINKED ISSUE #54: Sync the mobile application with and database

### PR DESCRIPTION
**Pull request by ImmortalIdiot**

### CODE REVIEW

**Review by NN171 — COMMENTED** [review]
Delete useless imports

**Comment by ImmortalIdiot** [comment]
It is temporarily forbidden to merge, the application crashes when logging in and registering!!!

**Review by NN171 — COMMENTED** [review]
Delete the unuse methods and imports from code

**Comment by ImmortalIdiot** [comment]
Xandr070, help me to fix displaying LoginFragment. I don't know how do it.
image

**Comment by ImmortalIdiot** [comment]
I don't undetstand why the design of login fragment is displayed this way. In branch "features/remember-me" everything is fine, but not in "develop" and "db/sync-db" branches.
image

**Comment by ImmortalIdiot** [comment]
I have fixed this issue.
image

**Review by Xandr070 — APPROVED** [review]

**Pull request merged**
